/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MediaMTX.API.Model;
using MediaMTX.API.Client;
using System.Reflection;

namespace MediaMTX.API.Test.Model
{
    /// <summary>
    ///  Class for testing AlwaysAvailableTrack
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AlwaysAvailableTrackTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AlwaysAvailableTrack
        //private AlwaysAvailableTrack instance;

        public AlwaysAvailableTrackTests()
        {
            // TODO uncomment below to create an instance of AlwaysAvailableTrack
            //instance = new AlwaysAvailableTrack();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AlwaysAvailableTrack
        /// </summary>
        [Fact]
        public void AlwaysAvailableTrackInstanceTest()
        {
            // TODO uncomment below to test "IsType" AlwaysAvailableTrack
            //Assert.IsType<AlwaysAvailableTrack>(instance);
        }

        /// <summary>
        /// Test the property 'ChannelCount'
        /// </summary>
        [Fact]
        public void ChannelCountTest()
        {
            // TODO unit test for the property 'ChannelCount'
        }

        /// <summary>
        /// Test the property 'Codec'
        /// </summary>
        [Fact]
        public void CodecTest()
        {
            // TODO unit test for the property 'Codec'
        }

        /// <summary>
        /// Test the property 'MuLaw'
        /// </summary>
        [Fact]
        public void MuLawTest()
        {
            // TODO unit test for the property 'MuLaw'
        }

        /// <summary>
        /// Test the property 'SampleRate'
        /// </summary>
        [Fact]
        public void SampleRateTest()
        {
            // TODO unit test for the property 'SampleRate'
        }
    }
}
