/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MediaMTX.API.Model;
using MediaMTX.API.Client;
using System.Reflection;

namespace MediaMTX.API.Test.Model
{
    /// <summary>
    ///  Class for testing HLSSession
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HLSSessionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HLSSession
        //private HLSSession instance;

        public HLSSessionTests()
        {
            // TODO uncomment below to create an instance of HLSSession
            //instance = new HLSSession();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HLSSession
        /// </summary>
        [Fact]
        public void HLSSessionInstanceTest()
        {
            // TODO uncomment below to test "IsType" HLSSession
            //Assert.IsType<HLSSession>(instance);
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'IsCDN'
        /// </summary>
        [Fact]
        public void IsCDNTest()
        {
            // TODO unit test for the property 'IsCDN'
        }

        /// <summary>
        /// Test the property 'OutboundBytes'
        /// </summary>
        [Fact]
        public void OutboundBytesTest()
        {
            // TODO unit test for the property 'OutboundBytes'
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'RemoteAddr'
        /// </summary>
        [Fact]
        public void RemoteAddrTest()
        {
            // TODO unit test for the property 'RemoteAddr'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
    }
}
