/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MediaMTX.API.Model;
using MediaMTX.API.Client;
using System.Reflection;

namespace MediaMTX.API.Test.Model
{
    /// <summary>
    ///  Class for testing PathConfList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PathConfListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PathConfList
        //private PathConfList instance;

        public PathConfListTests()
        {
            // TODO uncomment below to create an instance of PathConfList
            //instance = new PathConfList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PathConfList
        /// </summary>
        [Fact]
        public void PathConfListInstanceTest()
        {
            // TODO uncomment below to test "IsType" PathConfList
            //Assert.IsType<PathConfList>(instance);
        }

        /// <summary>
        /// Test the property 'ItemCount'
        /// </summary>
        [Fact]
        public void ItemCountTest()
        {
            // TODO unit test for the property 'ItemCount'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'PageCount'
        /// </summary>
        [Fact]
        public void PageCountTest()
        {
            // TODO unit test for the property 'PageCount'
        }
    }
}
