/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MediaMTX.API.Model;
using MediaMTX.API.Client;
using System.Reflection;

namespace MediaMTX.API.Test.Model
{
    /// <summary>
    ///  Class for testing PathTrackCodecPropsAV1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PathTrackCodecPropsAV1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PathTrackCodecPropsAV1
        //private PathTrackCodecPropsAV1 instance;

        public PathTrackCodecPropsAV1Tests()
        {
            // TODO uncomment below to create an instance of PathTrackCodecPropsAV1
            //instance = new PathTrackCodecPropsAV1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PathTrackCodecPropsAV1
        /// </summary>
        [Fact]
        public void PathTrackCodecPropsAV1InstanceTest()
        {
            // TODO uncomment below to test "IsType" PathTrackCodecPropsAV1
            //Assert.IsType<PathTrackCodecPropsAV1>(instance);
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Fact]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }

        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Fact]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }

        /// <summary>
        /// Test the property 'Tier'
        /// </summary>
        [Fact]
        public void TierTest()
        {
            // TODO unit test for the property 'Tier'
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
    }
}
