/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MediaMTX.API.Model;
using MediaMTX.API.Client;
using System.Reflection;

namespace MediaMTX.API.Test.Model
{
    /// <summary>
    ///  Class for testing PathConf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PathConfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PathConf
        //private PathConf instance;

        public PathConfTests()
        {
            // TODO uncomment below to create an instance of PathConf
            //instance = new PathConf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PathConf
        /// </summary>
        [Fact]
        public void PathConfInstanceTest()
        {
            // TODO uncomment below to test "IsType" PathConf
            //Assert.IsType<PathConf>(instance);
        }

        /// <summary>
        /// Test the property 'AlwaysAvailable'
        /// </summary>
        [Fact]
        public void AlwaysAvailableTest()
        {
            // TODO unit test for the property 'AlwaysAvailable'
        }

        /// <summary>
        /// Test the property 'AlwaysAvailableFile'
        /// </summary>
        [Fact]
        public void AlwaysAvailableFileTest()
        {
            // TODO unit test for the property 'AlwaysAvailableFile'
        }

        /// <summary>
        /// Test the property 'AlwaysAvailableTracks'
        /// </summary>
        [Fact]
        public void AlwaysAvailableTracksTest()
        {
            // TODO unit test for the property 'AlwaysAvailableTracks'
        }

        /// <summary>
        /// Test the property 'DisablePublisherOverride'
        /// </summary>
        [Fact]
        public void DisablePublisherOverrideTest()
        {
            // TODO unit test for the property 'DisablePublisherOverride'
        }

        /// <summary>
        /// Test the property 'Fallback'
        /// </summary>
        [Fact]
        public void FallbackTest()
        {
            // TODO unit test for the property 'Fallback'
        }

        /// <summary>
        /// Test the property 'MaxReaders'
        /// </summary>
        [Fact]
        public void MaxReadersTest()
        {
            // TODO unit test for the property 'MaxReaders'
        }

        /// <summary>
        /// Test the property 'MpegtsUDPReadBufferSize'
        /// </summary>
        [Fact]
        public void MpegtsUDPReadBufferSizeTest()
        {
            // TODO unit test for the property 'MpegtsUDPReadBufferSize'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'OverridePublisher'
        /// </summary>
        [Fact]
        public void OverridePublisherTest()
        {
            // TODO unit test for the property 'OverridePublisher'
        }

        /// <summary>
        /// Test the property 'Playback'
        /// </summary>
        [Fact]
        public void PlaybackTest()
        {
            // TODO unit test for the property 'Playback'
        }

        /// <summary>
        /// Test the property 'PublishIPs'
        /// </summary>
        [Fact]
        public void PublishIPsTest()
        {
            // TODO unit test for the property 'PublishIPs'
        }

        /// <summary>
        /// Test the property 'PublishPass'
        /// </summary>
        [Fact]
        public void PublishPassTest()
        {
            // TODO unit test for the property 'PublishPass'
        }

        /// <summary>
        /// Test the property 'PublishUser'
        /// </summary>
        [Fact]
        public void PublishUserTest()
        {
            // TODO unit test for the property 'PublishUser'
        }

        /// <summary>
        /// Test the property 'ReadIPs'
        /// </summary>
        [Fact]
        public void ReadIPsTest()
        {
            // TODO unit test for the property 'ReadIPs'
        }

        /// <summary>
        /// Test the property 'ReadPass'
        /// </summary>
        [Fact]
        public void ReadPassTest()
        {
            // TODO unit test for the property 'ReadPass'
        }

        /// <summary>
        /// Test the property 'ReadUser'
        /// </summary>
        [Fact]
        public void ReadUserTest()
        {
            // TODO unit test for the property 'ReadUser'
        }

        /// <summary>
        /// Test the property 'Record'
        /// </summary>
        [Fact]
        public void RecordTest()
        {
            // TODO unit test for the property 'Record'
        }

        /// <summary>
        /// Test the property 'RecordDeleteAfter'
        /// </summary>
        [Fact]
        public void RecordDeleteAfterTest()
        {
            // TODO unit test for the property 'RecordDeleteAfter'
        }

        /// <summary>
        /// Test the property 'RecordFormat'
        /// </summary>
        [Fact]
        public void RecordFormatTest()
        {
            // TODO unit test for the property 'RecordFormat'
        }

        /// <summary>
        /// Test the property 'RecordMaxPartSize'
        /// </summary>
        [Fact]
        public void RecordMaxPartSizeTest()
        {
            // TODO unit test for the property 'RecordMaxPartSize'
        }

        /// <summary>
        /// Test the property 'RecordPartDuration'
        /// </summary>
        [Fact]
        public void RecordPartDurationTest()
        {
            // TODO unit test for the property 'RecordPartDuration'
        }

        /// <summary>
        /// Test the property 'RecordPath'
        /// </summary>
        [Fact]
        public void RecordPathTest()
        {
            // TODO unit test for the property 'RecordPath'
        }

        /// <summary>
        /// Test the property 'RecordSegmentDuration'
        /// </summary>
        [Fact]
        public void RecordSegmentDurationTest()
        {
            // TODO unit test for the property 'RecordSegmentDuration'
        }

        /// <summary>
        /// Test the property 'RpiCameraAWB'
        /// </summary>
        [Fact]
        public void RpiCameraAWBTest()
        {
            // TODO unit test for the property 'RpiCameraAWB'
        }

        /// <summary>
        /// Test the property 'RpiCameraAWBGains'
        /// </summary>
        [Fact]
        public void RpiCameraAWBGainsTest()
        {
            // TODO unit test for the property 'RpiCameraAWBGains'
        }

        /// <summary>
        /// Test the property 'RpiCameraAfMode'
        /// </summary>
        [Fact]
        public void RpiCameraAfModeTest()
        {
            // TODO unit test for the property 'RpiCameraAfMode'
        }

        /// <summary>
        /// Test the property 'RpiCameraAfRange'
        /// </summary>
        [Fact]
        public void RpiCameraAfRangeTest()
        {
            // TODO unit test for the property 'RpiCameraAfRange'
        }

        /// <summary>
        /// Test the property 'RpiCameraAfSpeed'
        /// </summary>
        [Fact]
        public void RpiCameraAfSpeedTest()
        {
            // TODO unit test for the property 'RpiCameraAfSpeed'
        }

        /// <summary>
        /// Test the property 'RpiCameraAfWindow'
        /// </summary>
        [Fact]
        public void RpiCameraAfWindowTest()
        {
            // TODO unit test for the property 'RpiCameraAfWindow'
        }

        /// <summary>
        /// Test the property 'RpiCameraBitrate'
        /// </summary>
        [Fact]
        public void RpiCameraBitrateTest()
        {
            // TODO unit test for the property 'RpiCameraBitrate'
        }

        /// <summary>
        /// Test the property 'RpiCameraBrightness'
        /// </summary>
        [Fact]
        public void RpiCameraBrightnessTest()
        {
            // TODO unit test for the property 'RpiCameraBrightness'
        }

        /// <summary>
        /// Test the property 'RpiCameraCamID'
        /// </summary>
        [Fact]
        public void RpiCameraCamIDTest()
        {
            // TODO unit test for the property 'RpiCameraCamID'
        }

        /// <summary>
        /// Test the property 'RpiCameraCodec'
        /// </summary>
        [Fact]
        public void RpiCameraCodecTest()
        {
            // TODO unit test for the property 'RpiCameraCodec'
        }

        /// <summary>
        /// Test the property 'RpiCameraContrast'
        /// </summary>
        [Fact]
        public void RpiCameraContrastTest()
        {
            // TODO unit test for the property 'RpiCameraContrast'
        }

        /// <summary>
        /// Test the property 'RpiCameraDenoise'
        /// </summary>
        [Fact]
        public void RpiCameraDenoiseTest()
        {
            // TODO unit test for the property 'RpiCameraDenoise'
        }

        /// <summary>
        /// Test the property 'RpiCameraEV'
        /// </summary>
        [Fact]
        public void RpiCameraEVTest()
        {
            // TODO unit test for the property 'RpiCameraEV'
        }

        /// <summary>
        /// Test the property 'RpiCameraExposure'
        /// </summary>
        [Fact]
        public void RpiCameraExposureTest()
        {
            // TODO unit test for the property 'RpiCameraExposure'
        }

        /// <summary>
        /// Test the property 'RpiCameraFPS'
        /// </summary>
        [Fact]
        public void RpiCameraFPSTest()
        {
            // TODO unit test for the property 'RpiCameraFPS'
        }

        /// <summary>
        /// Test the property 'RpiCameraFlickerPeriod'
        /// </summary>
        [Fact]
        public void RpiCameraFlickerPeriodTest()
        {
            // TODO unit test for the property 'RpiCameraFlickerPeriod'
        }

        /// <summary>
        /// Test the property 'RpiCameraGain'
        /// </summary>
        [Fact]
        public void RpiCameraGainTest()
        {
            // TODO unit test for the property 'RpiCameraGain'
        }

        /// <summary>
        /// Test the property 'RpiCameraHDR'
        /// </summary>
        [Fact]
        public void RpiCameraHDRTest()
        {
            // TODO unit test for the property 'RpiCameraHDR'
        }

        /// <summary>
        /// Test the property 'RpiCameraHFlip'
        /// </summary>
        [Fact]
        public void RpiCameraHFlipTest()
        {
            // TODO unit test for the property 'RpiCameraHFlip'
        }

        /// <summary>
        /// Test the property 'RpiCameraHardwareH264Level'
        /// </summary>
        [Fact]
        public void RpiCameraHardwareH264LevelTest()
        {
            // TODO unit test for the property 'RpiCameraHardwareH264Level'
        }

        /// <summary>
        /// Test the property 'RpiCameraHardwareH264Profile'
        /// </summary>
        [Fact]
        public void RpiCameraHardwareH264ProfileTest()
        {
            // TODO unit test for the property 'RpiCameraHardwareH264Profile'
        }

        /// <summary>
        /// Test the property 'RpiCameraHeight'
        /// </summary>
        [Fact]
        public void RpiCameraHeightTest()
        {
            // TODO unit test for the property 'RpiCameraHeight'
        }

        /// <summary>
        /// Test the property 'RpiCameraIDRPeriod'
        /// </summary>
        [Fact]
        public void RpiCameraIDRPeriodTest()
        {
            // TODO unit test for the property 'RpiCameraIDRPeriod'
        }

        /// <summary>
        /// Test the property 'RpiCameraJPEGQuality'
        /// </summary>
        [Fact]
        public void RpiCameraJPEGQualityTest()
        {
            // TODO unit test for the property 'RpiCameraJPEGQuality'
        }

        /// <summary>
        /// Test the property 'RpiCameraLensPosition'
        /// </summary>
        [Fact]
        public void RpiCameraLensPositionTest()
        {
            // TODO unit test for the property 'RpiCameraLensPosition'
        }

        /// <summary>
        /// Test the property 'RpiCameraLevel'
        /// </summary>
        [Fact]
        public void RpiCameraLevelTest()
        {
            // TODO unit test for the property 'RpiCameraLevel'
        }

        /// <summary>
        /// Test the property 'RpiCameraMJPEGQuality'
        /// </summary>
        [Fact]
        public void RpiCameraMJPEGQualityTest()
        {
            // TODO unit test for the property 'RpiCameraMJPEGQuality'
        }

        /// <summary>
        /// Test the property 'RpiCameraMetering'
        /// </summary>
        [Fact]
        public void RpiCameraMeteringTest()
        {
            // TODO unit test for the property 'RpiCameraMetering'
        }

        /// <summary>
        /// Test the property 'RpiCameraMode'
        /// </summary>
        [Fact]
        public void RpiCameraModeTest()
        {
            // TODO unit test for the property 'RpiCameraMode'
        }

        /// <summary>
        /// Test the property 'RpiCameraProfile'
        /// </summary>
        [Fact]
        public void RpiCameraProfileTest()
        {
            // TODO unit test for the property 'RpiCameraProfile'
        }

        /// <summary>
        /// Test the property 'RpiCameraROI'
        /// </summary>
        [Fact]
        public void RpiCameraROITest()
        {
            // TODO unit test for the property 'RpiCameraROI'
        }

        /// <summary>
        /// Test the property 'RpiCameraSaturation'
        /// </summary>
        [Fact]
        public void RpiCameraSaturationTest()
        {
            // TODO unit test for the property 'RpiCameraSaturation'
        }

        /// <summary>
        /// Test the property 'RpiCameraSecondary'
        /// </summary>
        [Fact]
        public void RpiCameraSecondaryTest()
        {
            // TODO unit test for the property 'RpiCameraSecondary'
        }

        /// <summary>
        /// Test the property 'RpiCameraSharpness'
        /// </summary>
        [Fact]
        public void RpiCameraSharpnessTest()
        {
            // TODO unit test for the property 'RpiCameraSharpness'
        }

        /// <summary>
        /// Test the property 'RpiCameraShutter'
        /// </summary>
        [Fact]
        public void RpiCameraShutterTest()
        {
            // TODO unit test for the property 'RpiCameraShutter'
        }

        /// <summary>
        /// Test the property 'RpiCameraSoftwareH264Level'
        /// </summary>
        [Fact]
        public void RpiCameraSoftwareH264LevelTest()
        {
            // TODO unit test for the property 'RpiCameraSoftwareH264Level'
        }

        /// <summary>
        /// Test the property 'RpiCameraSoftwareH264Profile'
        /// </summary>
        [Fact]
        public void RpiCameraSoftwareH264ProfileTest()
        {
            // TODO unit test for the property 'RpiCameraSoftwareH264Profile'
        }

        /// <summary>
        /// Test the property 'RpiCameraTextOverlay'
        /// </summary>
        [Fact]
        public void RpiCameraTextOverlayTest()
        {
            // TODO unit test for the property 'RpiCameraTextOverlay'
        }

        /// <summary>
        /// Test the property 'RpiCameraTextOverlayEnable'
        /// </summary>
        [Fact]
        public void RpiCameraTextOverlayEnableTest()
        {
            // TODO unit test for the property 'RpiCameraTextOverlayEnable'
        }

        /// <summary>
        /// Test the property 'RpiCameraTuningFile'
        /// </summary>
        [Fact]
        public void RpiCameraTuningFileTest()
        {
            // TODO unit test for the property 'RpiCameraTuningFile'
        }

        /// <summary>
        /// Test the property 'RpiCameraVFlip'
        /// </summary>
        [Fact]
        public void RpiCameraVFlipTest()
        {
            // TODO unit test for the property 'RpiCameraVFlip'
        }

        /// <summary>
        /// Test the property 'RpiCameraWidth'
        /// </summary>
        [Fact]
        public void RpiCameraWidthTest()
        {
            // TODO unit test for the property 'RpiCameraWidth'
        }

        /// <summary>
        /// Test the property 'RtpSDP'
        /// </summary>
        [Fact]
        public void RtpSDPTest()
        {
            // TODO unit test for the property 'RtpSDP'
        }

        /// <summary>
        /// Test the property 'RtpUDPReadBufferSize'
        /// </summary>
        [Fact]
        public void RtpUDPReadBufferSizeTest()
        {
            // TODO unit test for the property 'RtpUDPReadBufferSize'
        }

        /// <summary>
        /// Test the property 'RtspAnyPort'
        /// </summary>
        [Fact]
        public void RtspAnyPortTest()
        {
            // TODO unit test for the property 'RtspAnyPort'
        }

        /// <summary>
        /// Test the property 'RtspDemuxMpegts'
        /// </summary>
        [Fact]
        public void RtspDemuxMpegtsTest()
        {
            // TODO unit test for the property 'RtspDemuxMpegts'
        }

        /// <summary>
        /// Test the property 'RtspRangeStart'
        /// </summary>
        [Fact]
        public void RtspRangeStartTest()
        {
            // TODO unit test for the property 'RtspRangeStart'
        }

        /// <summary>
        /// Test the property 'RtspRangeType'
        /// </summary>
        [Fact]
        public void RtspRangeTypeTest()
        {
            // TODO unit test for the property 'RtspRangeType'
        }

        /// <summary>
        /// Test the property 'RtspTransport'
        /// </summary>
        [Fact]
        public void RtspTransportTest()
        {
            // TODO unit test for the property 'RtspTransport'
        }

        /// <summary>
        /// Test the property 'RtspUDPReadBufferSize'
        /// </summary>
        [Fact]
        public void RtspUDPReadBufferSizeTest()
        {
            // TODO unit test for the property 'RtspUDPReadBufferSize'
        }

        /// <summary>
        /// Test the property 'RtspUDPSourcePortRange'
        /// </summary>
        [Fact]
        public void RtspUDPSourcePortRangeTest()
        {
            // TODO unit test for the property 'RtspUDPSourcePortRange'
        }

        /// <summary>
        /// Test the property 'RunOnDemand'
        /// </summary>
        [Fact]
        public void RunOnDemandTest()
        {
            // TODO unit test for the property 'RunOnDemand'
        }

        /// <summary>
        /// Test the property 'RunOnDemandCloseAfter'
        /// </summary>
        [Fact]
        public void RunOnDemandCloseAfterTest()
        {
            // TODO unit test for the property 'RunOnDemandCloseAfter'
        }

        /// <summary>
        /// Test the property 'RunOnDemandRestart'
        /// </summary>
        [Fact]
        public void RunOnDemandRestartTest()
        {
            // TODO unit test for the property 'RunOnDemandRestart'
        }

        /// <summary>
        /// Test the property 'RunOnDemandStartTimeout'
        /// </summary>
        [Fact]
        public void RunOnDemandStartTimeoutTest()
        {
            // TODO unit test for the property 'RunOnDemandStartTimeout'
        }

        /// <summary>
        /// Test the property 'RunOnInit'
        /// </summary>
        [Fact]
        public void RunOnInitTest()
        {
            // TODO unit test for the property 'RunOnInit'
        }

        /// <summary>
        /// Test the property 'RunOnInitRestart'
        /// </summary>
        [Fact]
        public void RunOnInitRestartTest()
        {
            // TODO unit test for the property 'RunOnInitRestart'
        }

        /// <summary>
        /// Test the property 'RunOnNotReady'
        /// </summary>
        [Fact]
        public void RunOnNotReadyTest()
        {
            // TODO unit test for the property 'RunOnNotReady'
        }

        /// <summary>
        /// Test the property 'RunOnRead'
        /// </summary>
        [Fact]
        public void RunOnReadTest()
        {
            // TODO unit test for the property 'RunOnRead'
        }

        /// <summary>
        /// Test the property 'RunOnReadRestart'
        /// </summary>
        [Fact]
        public void RunOnReadRestartTest()
        {
            // TODO unit test for the property 'RunOnReadRestart'
        }

        /// <summary>
        /// Test the property 'RunOnReady'
        /// </summary>
        [Fact]
        public void RunOnReadyTest()
        {
            // TODO unit test for the property 'RunOnReady'
        }

        /// <summary>
        /// Test the property 'RunOnReadyRestart'
        /// </summary>
        [Fact]
        public void RunOnReadyRestartTest()
        {
            // TODO unit test for the property 'RunOnReadyRestart'
        }

        /// <summary>
        /// Test the property 'RunOnRecordSegmentComplete'
        /// </summary>
        [Fact]
        public void RunOnRecordSegmentCompleteTest()
        {
            // TODO unit test for the property 'RunOnRecordSegmentComplete'
        }

        /// <summary>
        /// Test the property 'RunOnRecordSegmentCreate'
        /// </summary>
        [Fact]
        public void RunOnRecordSegmentCreateTest()
        {
            // TODO unit test for the property 'RunOnRecordSegmentCreate'
        }

        /// <summary>
        /// Test the property 'RunOnUnDemand'
        /// </summary>
        [Fact]
        public void RunOnUnDemandTest()
        {
            // TODO unit test for the property 'RunOnUnDemand'
        }

        /// <summary>
        /// Test the property 'RunOnUnread'
        /// </summary>
        [Fact]
        public void RunOnUnreadTest()
        {
            // TODO unit test for the property 'RunOnUnread'
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

        /// <summary>
        /// Test the property 'SourceAnyPortEnable'
        /// </summary>
        [Fact]
        public void SourceAnyPortEnableTest()
        {
            // TODO unit test for the property 'SourceAnyPortEnable'
        }

        /// <summary>
        /// Test the property 'SourceFingerprint'
        /// </summary>
        [Fact]
        public void SourceFingerprintTest()
        {
            // TODO unit test for the property 'SourceFingerprint'
        }

        /// <summary>
        /// Test the property 'SourceOnDemand'
        /// </summary>
        [Fact]
        public void SourceOnDemandTest()
        {
            // TODO unit test for the property 'SourceOnDemand'
        }

        /// <summary>
        /// Test the property 'SourceOnDemandCloseAfter'
        /// </summary>
        [Fact]
        public void SourceOnDemandCloseAfterTest()
        {
            // TODO unit test for the property 'SourceOnDemandCloseAfter'
        }

        /// <summary>
        /// Test the property 'SourceOnDemandStartTimeout'
        /// </summary>
        [Fact]
        public void SourceOnDemandStartTimeoutTest()
        {
            // TODO unit test for the property 'SourceOnDemandStartTimeout'
        }

        /// <summary>
        /// Test the property 'SourceProtocol'
        /// </summary>
        [Fact]
        public void SourceProtocolTest()
        {
            // TODO unit test for the property 'SourceProtocol'
        }

        /// <summary>
        /// Test the property 'SourceRedirect'
        /// </summary>
        [Fact]
        public void SourceRedirectTest()
        {
            // TODO unit test for the property 'SourceRedirect'
        }

        /// <summary>
        /// Test the property 'SrtPublishPassphrase'
        /// </summary>
        [Fact]
        public void SrtPublishPassphraseTest()
        {
            // TODO unit test for the property 'SrtPublishPassphrase'
        }

        /// <summary>
        /// Test the property 'SrtReadPassphrase'
        /// </summary>
        [Fact]
        public void SrtReadPassphraseTest()
        {
            // TODO unit test for the property 'SrtReadPassphrase'
        }

        /// <summary>
        /// Test the property 'UseAbsoluteTimestamp'
        /// </summary>
        [Fact]
        public void UseAbsoluteTimestampTest()
        {
            // TODO unit test for the property 'UseAbsoluteTimestamp'
        }

        /// <summary>
        /// Test the property 'WhepBearerToken'
        /// </summary>
        [Fact]
        public void WhepBearerTokenTest()
        {
            // TODO unit test for the property 'WhepBearerToken'
        }

        /// <summary>
        /// Test the property 'WhepHandshakeTimeout'
        /// </summary>
        [Fact]
        public void WhepHandshakeTimeoutTest()
        {
            // TODO unit test for the property 'WhepHandshakeTimeout'
        }

        /// <summary>
        /// Test the property 'WhepSTUNGatherTimeout'
        /// </summary>
        [Fact]
        public void WhepSTUNGatherTimeoutTest()
        {
            // TODO unit test for the property 'WhepSTUNGatherTimeout'
        }

        /// <summary>
        /// Test the property 'WhepTrackGatherTimeout'
        /// </summary>
        [Fact]
        public void WhepTrackGatherTimeoutTest()
        {
            // TODO unit test for the property 'WhepTrackGatherTimeout'
        }
    }
}
