/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MediaMTX.API.Model;
using MediaMTX.API.Client;
using System.Reflection;

namespace MediaMTX.API.Test.Model
{
    /// <summary>
    ///  Class for testing PathTrackCodecPropsAC3
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PathTrackCodecPropsAC3Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PathTrackCodecPropsAC3
        //private PathTrackCodecPropsAC3 instance;

        public PathTrackCodecPropsAC3Tests()
        {
            // TODO uncomment below to create an instance of PathTrackCodecPropsAC3
            //instance = new PathTrackCodecPropsAC3();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PathTrackCodecPropsAC3
        /// </summary>
        [Fact]
        public void PathTrackCodecPropsAC3InstanceTest()
        {
            // TODO uncomment below to test "IsType" PathTrackCodecPropsAC3
            //Assert.IsType<PathTrackCodecPropsAC3>(instance);
        }

        /// <summary>
        /// Test the property 'ChannelCount'
        /// </summary>
        [Fact]
        public void ChannelCountTest()
        {
            // TODO unit test for the property 'ChannelCount'
        }

        /// <summary>
        /// Test the property 'SampleRate'
        /// </summary>
        [Fact]
        public void SampleRateTest()
        {
            // TODO unit test for the property 'SampleRate'
        }
    }
}
