/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MediaMTX.API.Model;
using MediaMTX.API.Client;
using System.Reflection;

namespace MediaMTX.API.Test.Model
{
    /// <summary>
    ///  Class for testing PathTrack
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PathTrackTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PathTrack
        //private PathTrack instance;

        public PathTrackTests()
        {
            // TODO uncomment below to create an instance of PathTrack
            //instance = new PathTrack();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PathTrack
        /// </summary>
        [Fact]
        public void PathTrackInstanceTest()
        {
            // TODO uncomment below to test "IsType" PathTrack
            //Assert.IsType<PathTrack>(instance);
        }

        /// <summary>
        /// Test the property 'Codec'
        /// </summary>
        [Fact]
        public void CodecTest()
        {
            // TODO unit test for the property 'Codec'
        }

        /// <summary>
        /// Test the property 'CodecProps'
        /// </summary>
        [Fact]
        public void CodecPropsTest()
        {
            // TODO unit test for the property 'CodecProps'
        }
    }
}
