/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MediaMTX.API.Model;
using MediaMTX.API.Client;
using System.Reflection;

namespace MediaMTX.API.Test.Model
{
    /// <summary>
    ///  Class for testing PathTrackCodecProps
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PathTrackCodecPropsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PathTrackCodecProps
        //private PathTrackCodecProps instance;

        public PathTrackCodecPropsTests()
        {
            // TODO uncomment below to create an instance of PathTrackCodecProps
            //instance = new PathTrackCodecProps();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PathTrackCodecProps
        /// </summary>
        [Fact]
        public void PathTrackCodecPropsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PathTrackCodecProps
            //Assert.IsType<PathTrackCodecProps>(instance);
        }
    }
}
