/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MediaMTX.API.Model;
using MediaMTX.API.Client;
using System.Reflection;

namespace MediaMTX.API.Test.Model
{
    /// <summary>
    ///  Class for testing PathTrackCodecPropsLPCM
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PathTrackCodecPropsLPCMTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PathTrackCodecPropsLPCM
        //private PathTrackCodecPropsLPCM instance;

        public PathTrackCodecPropsLPCMTests()
        {
            // TODO uncomment below to create an instance of PathTrackCodecPropsLPCM
            //instance = new PathTrackCodecPropsLPCM();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PathTrackCodecPropsLPCM
        /// </summary>
        [Fact]
        public void PathTrackCodecPropsLPCMInstanceTest()
        {
            // TODO uncomment below to test "IsType" PathTrackCodecPropsLPCM
            //Assert.IsType<PathTrackCodecPropsLPCM>(instance);
        }

        /// <summary>
        /// Test the property 'BitDepth'
        /// </summary>
        [Fact]
        public void BitDepthTest()
        {
            // TODO unit test for the property 'BitDepth'
        }

        /// <summary>
        /// Test the property 'ChannelCount'
        /// </summary>
        [Fact]
        public void ChannelCountTest()
        {
            // TODO unit test for the property 'ChannelCount'
        }

        /// <summary>
        /// Test the property 'SampleRate'
        /// </summary>
        [Fact]
        public void SampleRateTest()
        {
            // TODO unit test for the property 'SampleRate'
        }
    }
}
