/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MediaMTX.API.Model;
using MediaMTX.API.Client;
using System.Reflection;

namespace MediaMTX.API.Test.Model
{
    /// <summary>
    ///  Class for testing RTMPConn
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RTMPConnTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RTMPConn
        //private RTMPConn instance;

        public RTMPConnTests()
        {
            // TODO uncomment below to create an instance of RTMPConn
            //instance = new RTMPConn();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RTMPConn
        /// </summary>
        [Fact]
        public void RTMPConnInstanceTest()
        {
            // TODO uncomment below to test "IsType" RTMPConn
            //Assert.IsType<RTMPConn>(instance);
        }

        /// <summary>
        /// Test the property 'BytesReceived'
        /// </summary>
        [Fact]
        public void BytesReceivedTest()
        {
            // TODO unit test for the property 'BytesReceived'
        }

        /// <summary>
        /// Test the property 'BytesSent'
        /// </summary>
        [Fact]
        public void BytesSentTest()
        {
            // TODO unit test for the property 'BytesSent'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'InboundBytes'
        /// </summary>
        [Fact]
        public void InboundBytesTest()
        {
            // TODO unit test for the property 'InboundBytes'
        }

        /// <summary>
        /// Test the property 'OutboundBytes'
        /// </summary>
        [Fact]
        public void OutboundBytesTest()
        {
            // TODO unit test for the property 'OutboundBytes'
        }

        /// <summary>
        /// Test the property 'OutboundFramesDiscarded'
        /// </summary>
        [Fact]
        public void OutboundFramesDiscardedTest()
        {
            // TODO unit test for the property 'OutboundFramesDiscarded'
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'RemoteAddr'
        /// </summary>
        [Fact]
        public void RemoteAddrTest()
        {
            // TODO unit test for the property 'RemoteAddr'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
    }
}
