/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MediaMTX.API.Model;
using MediaMTX.API.Client;
using System.Reflection;

namespace MediaMTX.API.Test.Model
{
    /// <summary>
    ///  Class for testing RTMPConnState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RTMPConnStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RTMPConnState
        //private RTMPConnState instance;

        public RTMPConnStateTests()
        {
            // TODO uncomment below to create an instance of RTMPConnState
            //instance = new RTMPConnState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RTMPConnState
        /// </summary>
        [Fact]
        public void RTMPConnStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" RTMPConnState
            //Assert.IsType<RTMPConnState>(instance);
        }
    }
}
