/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MediaMTX.API.Model;
using MediaMTX.API.Client;
using System.Reflection;

namespace MediaMTX.API.Test.Model
{
    /// <summary>
    ///  Class for testing RTSPSession
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RTSPSessionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RTSPSession
        //private RTSPSession instance;

        public RTSPSessionTests()
        {
            // TODO uncomment below to create an instance of RTSPSession
            //instance = new RTSPSession();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RTSPSession
        /// </summary>
        [Fact]
        public void RTSPSessionInstanceTest()
        {
            // TODO uncomment below to test "IsType" RTSPSession
            //Assert.IsType<RTSPSession>(instance);
        }

        /// <summary>
        /// Test the property 'BytesReceived'
        /// </summary>
        [Fact]
        public void BytesReceivedTest()
        {
            // TODO unit test for the property 'BytesReceived'
        }

        /// <summary>
        /// Test the property 'BytesSent'
        /// </summary>
        [Fact]
        public void BytesSentTest()
        {
            // TODO unit test for the property 'BytesSent'
        }

        /// <summary>
        /// Test the property 'Conns'
        /// </summary>
        [Fact]
        public void ConnsTest()
        {
            // TODO unit test for the property 'Conns'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'InboundBytes'
        /// </summary>
        [Fact]
        public void InboundBytesTest()
        {
            // TODO unit test for the property 'InboundBytes'
        }

        /// <summary>
        /// Test the property 'InboundRTCPPackets'
        /// </summary>
        [Fact]
        public void InboundRTCPPacketsTest()
        {
            // TODO unit test for the property 'InboundRTCPPackets'
        }

        /// <summary>
        /// Test the property 'InboundRTCPPacketsInError'
        /// </summary>
        [Fact]
        public void InboundRTCPPacketsInErrorTest()
        {
            // TODO unit test for the property 'InboundRTCPPacketsInError'
        }

        /// <summary>
        /// Test the property 'InboundRTPPackets'
        /// </summary>
        [Fact]
        public void InboundRTPPacketsTest()
        {
            // TODO unit test for the property 'InboundRTPPackets'
        }

        /// <summary>
        /// Test the property 'InboundRTPPacketsInError'
        /// </summary>
        [Fact]
        public void InboundRTPPacketsInErrorTest()
        {
            // TODO unit test for the property 'InboundRTPPacketsInError'
        }

        /// <summary>
        /// Test the property 'InboundRTPPacketsJitter'
        /// </summary>
        [Fact]
        public void InboundRTPPacketsJitterTest()
        {
            // TODO unit test for the property 'InboundRTPPacketsJitter'
        }

        /// <summary>
        /// Test the property 'InboundRTPPacketsLost'
        /// </summary>
        [Fact]
        public void InboundRTPPacketsLostTest()
        {
            // TODO unit test for the property 'InboundRTPPacketsLost'
        }

        /// <summary>
        /// Test the property 'OutboundBytes'
        /// </summary>
        [Fact]
        public void OutboundBytesTest()
        {
            // TODO unit test for the property 'OutboundBytes'
        }

        /// <summary>
        /// Test the property 'OutboundRTCPPackets'
        /// </summary>
        [Fact]
        public void OutboundRTCPPacketsTest()
        {
            // TODO unit test for the property 'OutboundRTCPPackets'
        }

        /// <summary>
        /// Test the property 'OutboundRTPPackets'
        /// </summary>
        [Fact]
        public void OutboundRTPPacketsTest()
        {
            // TODO unit test for the property 'OutboundRTPPackets'
        }

        /// <summary>
        /// Test the property 'OutboundRTPPacketsDiscarded'
        /// </summary>
        [Fact]
        public void OutboundRTPPacketsDiscardedTest()
        {
            // TODO unit test for the property 'OutboundRTPPacketsDiscarded'
        }

        /// <summary>
        /// Test the property 'OutboundRTPPacketsReportedLost'
        /// </summary>
        [Fact]
        public void OutboundRTPPacketsReportedLostTest()
        {
            // TODO unit test for the property 'OutboundRTPPacketsReportedLost'
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Fact]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'RemoteAddr'
        /// </summary>
        [Fact]
        public void RemoteAddrTest()
        {
            // TODO unit test for the property 'RemoteAddr'
        }

        /// <summary>
        /// Test the property 'RtcpPacketsInError'
        /// </summary>
        [Fact]
        public void RtcpPacketsInErrorTest()
        {
            // TODO unit test for the property 'RtcpPacketsInError'
        }

        /// <summary>
        /// Test the property 'RtcpPacketsReceived'
        /// </summary>
        [Fact]
        public void RtcpPacketsReceivedTest()
        {
            // TODO unit test for the property 'RtcpPacketsReceived'
        }

        /// <summary>
        /// Test the property 'RtcpPacketsSent'
        /// </summary>
        [Fact]
        public void RtcpPacketsSentTest()
        {
            // TODO unit test for the property 'RtcpPacketsSent'
        }

        /// <summary>
        /// Test the property 'RtpPacketsInError'
        /// </summary>
        [Fact]
        public void RtpPacketsInErrorTest()
        {
            // TODO unit test for the property 'RtpPacketsInError'
        }

        /// <summary>
        /// Test the property 'RtpPacketsJitter'
        /// </summary>
        [Fact]
        public void RtpPacketsJitterTest()
        {
            // TODO unit test for the property 'RtpPacketsJitter'
        }

        /// <summary>
        /// Test the property 'RtpPacketsLost'
        /// </summary>
        [Fact]
        public void RtpPacketsLostTest()
        {
            // TODO unit test for the property 'RtpPacketsLost'
        }

        /// <summary>
        /// Test the property 'RtpPacketsReceived'
        /// </summary>
        [Fact]
        public void RtpPacketsReceivedTest()
        {
            // TODO unit test for the property 'RtpPacketsReceived'
        }

        /// <summary>
        /// Test the property 'RtpPacketsSent'
        /// </summary>
        [Fact]
        public void RtpPacketsSentTest()
        {
            // TODO unit test for the property 'RtpPacketsSent'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Transport'
        /// </summary>
        [Fact]
        public void TransportTest()
        {
            // TODO unit test for the property 'Transport'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
    }
}
