/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MediaMTX.API.Model;
using MediaMTX.API.Client;
using System.Reflection;

namespace MediaMTX.API.Test.Model
{
    /// <summary>
    ///  Class for testing RTSPConn
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RTSPConnTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RTSPConn
        //private RTSPConn instance;

        public RTSPConnTests()
        {
            // TODO uncomment below to create an instance of RTSPConn
            //instance = new RTSPConn();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RTSPConn
        /// </summary>
        [Fact]
        public void RTSPConnInstanceTest()
        {
            // TODO uncomment below to test "IsType" RTSPConn
            //Assert.IsType<RTSPConn>(instance);
        }

        /// <summary>
        /// Test the property 'BytesReceived'
        /// </summary>
        [Fact]
        public void BytesReceivedTest()
        {
            // TODO unit test for the property 'BytesReceived'
        }

        /// <summary>
        /// Test the property 'BytesSent'
        /// </summary>
        [Fact]
        public void BytesSentTest()
        {
            // TODO unit test for the property 'BytesSent'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'InboundBytes'
        /// </summary>
        [Fact]
        public void InboundBytesTest()
        {
            // TODO unit test for the property 'InboundBytes'
        }

        /// <summary>
        /// Test the property 'OutboundBytes'
        /// </summary>
        [Fact]
        public void OutboundBytesTest()
        {
            // TODO unit test for the property 'OutboundBytes'
        }

        /// <summary>
        /// Test the property 'RemoteAddr'
        /// </summary>
        [Fact]
        public void RemoteAddrTest()
        {
            // TODO unit test for the property 'RemoteAddr'
        }

        /// <summary>
        /// Test the property 'Session'
        /// </summary>
        [Fact]
        public void SessionTest()
        {
            // TODO unit test for the property 'Session'
        }

        /// <summary>
        /// Test the property 'Tunnel'
        /// </summary>
        [Fact]
        public void TunnelTest()
        {
            // TODO unit test for the property 'Tunnel'
        }
    }
}
