/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MediaMTX.API.Model;
using MediaMTX.API.Client;
using System.Reflection;

namespace MediaMTX.API.Test.Model
{
    /// <summary>
    ///  Class for testing WebRTCICEServer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebRTCICEServerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebRTCICEServer
        //private WebRTCICEServer instance;

        public WebRTCICEServerTests()
        {
            // TODO uncomment below to create an instance of WebRTCICEServer
            //instance = new WebRTCICEServer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebRTCICEServer
        /// </summary>
        [Fact]
        public void WebRTCICEServerInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebRTCICEServer
            //Assert.IsType<WebRTCICEServer>(instance);
        }

        /// <summary>
        /// Test the property 'ClientOnly'
        /// </summary>
        [Fact]
        public void ClientOnlyTest()
        {
            // TODO unit test for the property 'ClientOnly'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
    }
}
