// <auto-generated>
/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MediaMTX.API.Client;

namespace MediaMTX.API.Model
{
    /// <summary>
    /// AuthInternalUserPermission
    /// </summary>
    public partial class AuthInternalUserPermission : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthInternalUserPermission" /> class.
        /// </summary>
        /// <param name="action">action</param>
        /// <param name="path">path</param>
        [JsonConstructor]
        public AuthInternalUserPermission(Option<AuthAction?> action = default, Option<string> path = default)
        {
            ActionOption = action;
            PathOption = path;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Action
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AuthAction?> ActionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [JsonPropertyName("action")]
        public AuthAction? Action { get { return this.ActionOption; } set { this.ActionOption = new Option<AuthAction?>(value); } }

        /// <summary>
        /// Used to track the state of Path
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> PathOption { get; private set; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [JsonPropertyName("path")]
        public string Path { get { return this.PathOption; } set { this.PathOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthInternalUserPermission {\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AuthInternalUserPermission" />
    /// </summary>
    public class AuthInternalUserPermissionJsonConverter : JsonConverter<AuthInternalUserPermission>
    {
        /// <summary>
        /// Deserializes json to <see cref="AuthInternalUserPermission" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AuthInternalUserPermission Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<AuthAction?> action = default;
            Option<string> path = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "action":
                            string actionRawValue = utf8JsonReader.GetString();
                            if (actionRawValue != null)
                                action = new Option<AuthAction?>(AuthActionValueConverter.FromStringOrDefault(actionRawValue));
                            break;
                        case "path":
                            path = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (action.IsSet && action.Value == null)
                throw new ArgumentNullException(nameof(action), "Property is not nullable for class AuthInternalUserPermission.");

            if (path.IsSet && path.Value == null)
                throw new ArgumentNullException(nameof(path), "Property is not nullable for class AuthInternalUserPermission.");

            return new AuthInternalUserPermission(action, path);
        }

        /// <summary>
        /// Serializes a <see cref="AuthInternalUserPermission" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="authInternalUserPermission"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AuthInternalUserPermission authInternalUserPermission, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, authInternalUserPermission, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AuthInternalUserPermission" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="authInternalUserPermission"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AuthInternalUserPermission authInternalUserPermission, JsonSerializerOptions jsonSerializerOptions)
        {
            if (authInternalUserPermission.PathOption.IsSet && authInternalUserPermission.Path == null)
                throw new ArgumentNullException(nameof(authInternalUserPermission.Path), "Property is required for class AuthInternalUserPermission.");

            if (authInternalUserPermission.ActionOption.IsSet)
            {
                var actionRawValue = AuthActionValueConverter.ToJsonValue(authInternalUserPermission.Action.Value);
                writer.WriteString("action", actionRawValue);
            }
            if (authInternalUserPermission.PathOption.IsSet)
                writer.WriteString("path", authInternalUserPermission.Path);
        }
    }
}
