// <auto-generated>
/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MediaMTX.API.Client;

namespace MediaMTX.API.Model
{
    /// <summary>
    /// Defines AuthMethod
    /// </summary>
    public enum AuthMethod
    {
        /// <summary>
        /// Enum Internal for value: internal
        /// </summary>
        Internal = 1,

        /// <summary>
        /// Enum Http for value: http
        /// </summary>
        Http = 2,

        /// <summary>
        /// Enum Jwt for value: jwt
        /// </summary>
        Jwt = 3
    }

    /// <summary>
    /// Converts <see cref="AuthMethod"/> to and from the JSON value
    /// </summary>
    public static class AuthMethodValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="AuthMethod"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static AuthMethod FromString(string value)
        {
            if (value.Equals("internal"))
                return AuthMethod.Internal;

            if (value.Equals("http"))
                return AuthMethod.Http;

            if (value.Equals("jwt"))
                return AuthMethod.Jwt;

            throw new NotImplementedException($"Could not convert value to type AuthMethod: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="AuthMethod"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static AuthMethod? FromStringOrDefault(string value)
        {
            if (value.Equals("internal"))
                return AuthMethod.Internal;

            if (value.Equals("http"))
                return AuthMethod.Http;

            if (value.Equals("jwt"))
                return AuthMethod.Jwt;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="AuthMethod"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(AuthMethod value)
        {
            if (value == AuthMethod.Internal)
                return "internal";

            if (value == AuthMethod.Http)
                return "http";

            if (value == AuthMethod.Jwt)
                return "jwt";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AuthMethod"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class AuthMethodJsonConverter : JsonConverter<AuthMethod>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override AuthMethod Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            AuthMethod? result = rawValue == null
                ? null
                : AuthMethodValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the AuthMethod to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="authMethod"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, AuthMethod authMethod, JsonSerializerOptions options)
        {
            writer.WriteStringValue(authMethod.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AuthMethod"/>
    /// </summary>
    public class AuthMethodNullableJsonConverter : JsonConverter<AuthMethod?>
    {
        /// <summary>
        /// Returns a AuthMethod from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override AuthMethod? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            AuthMethod? result = rawValue == null
                ? null
                : AuthMethodValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="authMethod"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, AuthMethod? authMethod, JsonSerializerOptions options)
        {
            writer.WriteStringValue(authMethod?.ToString() ?? "null");
        }
    }
}
