// <auto-generated>
/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MediaMTX.API.Client;

namespace MediaMTX.API.Model
{
    /// <summary>
    /// Defines HLSVariant
    /// </summary>
    public enum HLSVariant
    {
        /// <summary>
        /// Enum Mpegts for value: mpegts
        /// </summary>
        Mpegts = 1,

        /// <summary>
        /// Enum Fmp4 for value: fmp4
        /// </summary>
        Fmp4 = 2,

        /// <summary>
        /// Enum LowLatency for value: lowLatency
        /// </summary>
        LowLatency = 3
    }

    /// <summary>
    /// Converts <see cref="HLSVariant"/> to and from the JSON value
    /// </summary>
    public static class HLSVariantValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="HLSVariant"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static HLSVariant FromString(string value)
        {
            if (value.Equals("mpegts"))
                return HLSVariant.Mpegts;

            if (value.Equals("fmp4"))
                return HLSVariant.Fmp4;

            if (value.Equals("lowLatency"))
                return HLSVariant.LowLatency;

            throw new NotImplementedException($"Could not convert value to type HLSVariant: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="HLSVariant"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static HLSVariant? FromStringOrDefault(string value)
        {
            if (value.Equals("mpegts"))
                return HLSVariant.Mpegts;

            if (value.Equals("fmp4"))
                return HLSVariant.Fmp4;

            if (value.Equals("lowLatency"))
                return HLSVariant.LowLatency;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="HLSVariant"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(HLSVariant value)
        {
            if (value == HLSVariant.Mpegts)
                return "mpegts";

            if (value == HLSVariant.Fmp4)
                return "fmp4";

            if (value == HLSVariant.LowLatency)
                return "lowLatency";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HLSVariant"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class HLSVariantJsonConverter : JsonConverter<HLSVariant>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override HLSVariant Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            HLSVariant? result = rawValue == null
                ? null
                : HLSVariantValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the HLSVariant to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="hLSVariant"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, HLSVariant hLSVariant, JsonSerializerOptions options)
        {
            writer.WriteStringValue(hLSVariant.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HLSVariant"/>
    /// </summary>
    public class HLSVariantNullableJsonConverter : JsonConverter<HLSVariant?>
    {
        /// <summary>
        /// Returns a HLSVariant from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override HLSVariant? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            HLSVariant? result = rawValue == null
                ? null
                : HLSVariantValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="hLSVariant"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, HLSVariant? hLSVariant, JsonSerializerOptions options)
        {
            writer.WriteStringValue(hLSVariant?.ToString() ?? "null");
        }
    }
}
