// <auto-generated>
/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MediaMTX.API.Client;

namespace MediaMTX.API.Model
{
    /// <summary>
    /// PathTrackCodecPropsVP9
    /// </summary>
    public partial class PathTrackCodecPropsVP9 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PathTrackCodecPropsVP9" /> class.
        /// </summary>
        /// <param name="profile">profile</param>
        [JsonConstructor]
        public PathTrackCodecPropsVP9(Option<long?> profile = default)
        {
            ProfileOption = profile;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Profile
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> ProfileOption { get; private set; }

        /// <summary>
        /// Gets or Sets Profile
        /// </summary>
        [JsonPropertyName("profile")]
        public long? Profile { get { return this.ProfileOption; } set { this.ProfileOption = new Option<long?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PathTrackCodecPropsVP9 {\n");
            sb.Append("  Profile: ").Append(Profile).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PathTrackCodecPropsVP9" />
    /// </summary>
    public class PathTrackCodecPropsVP9JsonConverter : JsonConverter<PathTrackCodecPropsVP9>
    {
        /// <summary>
        /// Deserializes json to <see cref="PathTrackCodecPropsVP9" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PathTrackCodecPropsVP9 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> profile = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "profile":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                profile = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (profile.IsSet && profile.Value == null)
                throw new ArgumentNullException(nameof(profile), "Property is not nullable for class PathTrackCodecPropsVP9.");

            return new PathTrackCodecPropsVP9(profile);
        }

        /// <summary>
        /// Serializes a <see cref="PathTrackCodecPropsVP9" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pathTrackCodecPropsVP9"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PathTrackCodecPropsVP9 pathTrackCodecPropsVP9, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, pathTrackCodecPropsVP9, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PathTrackCodecPropsVP9" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pathTrackCodecPropsVP9"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PathTrackCodecPropsVP9 pathTrackCodecPropsVP9, JsonSerializerOptions jsonSerializerOptions)
        {
            if (pathTrackCodecPropsVP9.ProfileOption.IsSet)
                writer.WriteNumber("profile", pathTrackCodecPropsVP9.ProfileOption.Value.Value);
        }
    }
}
