// <auto-generated>
/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MediaMTX.API.Client;

namespace MediaMTX.API.Model
{
    /// <summary>
    /// PathTrack
    /// </summary>
    public partial class PathTrack : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PathTrack" /> class.
        /// </summary>
        /// <param name="codec">codec</param>
        /// <param name="codecProps">codecProps</param>
        [JsonConstructor]
        public PathTrack(Option<PathTrackCodec?> codec = default, Option<PathTrackCodecProps> codecProps = default)
        {
            CodecOption = codec;
            CodecPropsOption = codecProps;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Codec
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<PathTrackCodec?> CodecOption { get; private set; }

        /// <summary>
        /// Gets or Sets Codec
        /// </summary>
        [JsonPropertyName("codec")]
        public PathTrackCodec? Codec { get { return this.CodecOption; } set { this.CodecOption = new Option<PathTrackCodec?>(value); } }

        /// <summary>
        /// Used to track the state of CodecProps
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<PathTrackCodecProps> CodecPropsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CodecProps
        /// </summary>
        [JsonPropertyName("codecProps")]
        public PathTrackCodecProps CodecProps { get { return this.CodecPropsOption; } set { this.CodecPropsOption = new Option<PathTrackCodecProps>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PathTrack {\n");
            sb.Append("  Codec: ").Append(Codec).Append("\n");
            sb.Append("  CodecProps: ").Append(CodecProps).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PathTrack" />
    /// </summary>
    public class PathTrackJsonConverter : JsonConverter<PathTrack>
    {
        /// <summary>
        /// Deserializes json to <see cref="PathTrack" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PathTrack Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PathTrackCodec?> codec = default;
            Option<PathTrackCodecProps> codecProps = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "codec":
                            string codecRawValue = utf8JsonReader.GetString();
                            if (codecRawValue != null)
                                codec = new Option<PathTrackCodec?>(PathTrackCodecValueConverter.FromStringOrDefault(codecRawValue));
                            break;
                        case "codecProps":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                codecProps = new Option<PathTrackCodecProps>(JsonSerializer.Deserialize<PathTrackCodecProps>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (codec.IsSet && codec.Value == null)
                throw new ArgumentNullException(nameof(codec), "Property is not nullable for class PathTrack.");

            return new PathTrack(codec, codecProps);
        }

        /// <summary>
        /// Serializes a <see cref="PathTrack" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pathTrack"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PathTrack pathTrack, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, pathTrack, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PathTrack" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pathTrack"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PathTrack pathTrack, JsonSerializerOptions jsonSerializerOptions)
        {
            if (pathTrack.CodecOption.IsSet)
            {
                var codecRawValue = PathTrackCodecValueConverter.ToJsonValue(pathTrack.Codec.Value);
                writer.WriteString("codec", codecRawValue);
            }
            if (pathTrack.CodecPropsOption.IsSet)
                if (pathTrack.CodecPropsOption.Value != null)
                {
                    writer.WritePropertyName("codecProps");
                    JsonSerializer.Serialize(writer, pathTrack.CodecProps, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("codecProps");
        }
    }
}
