// <auto-generated>
/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MediaMTX.API.Client;

namespace MediaMTX.API.Model
{
    /// <summary>
    /// Defines PathSourceType
    /// </summary>
    public enum PathSourceType
    {
        /// <summary>
        /// Enum HlsSource for value: hlsSource
        /// </summary>
        HlsSource = 1,

        /// <summary>
        /// Enum Redirect for value: redirect
        /// </summary>
        Redirect = 2,

        /// <summary>
        /// Enum RpiCameraSource for value: rpiCameraSource
        /// </summary>
        RpiCameraSource = 3,

        /// <summary>
        /// Enum RtmpConn for value: rtmpConn
        /// </summary>
        RtmpConn = 4,

        /// <summary>
        /// Enum RtmpsConn for value: rtmpsConn
        /// </summary>
        RtmpsConn = 5,

        /// <summary>
        /// Enum RtmpSource for value: rtmpSource
        /// </summary>
        RtmpSource = 6,

        /// <summary>
        /// Enum RtspSession for value: rtspSession
        /// </summary>
        RtspSession = 7,

        /// <summary>
        /// Enum RtspSource for value: rtspSource
        /// </summary>
        RtspSource = 8,

        /// <summary>
        /// Enum RtspsSession for value: rtspsSession
        /// </summary>
        RtspsSession = 9,

        /// <summary>
        /// Enum SrtConn for value: srtConn
        /// </summary>
        SrtConn = 10,

        /// <summary>
        /// Enum SrtSource for value: srtSource
        /// </summary>
        SrtSource = 11,

        /// <summary>
        /// Enum MpegtsSource for value: mpegtsSource
        /// </summary>
        MpegtsSource = 12,

        /// <summary>
        /// Enum RtpSource for value: rtpSource
        /// </summary>
        RtpSource = 13,

        /// <summary>
        /// Enum WebRTCSession for value: webRTCSession
        /// </summary>
        WebRTCSession = 14,

        /// <summary>
        /// Enum WebRTCSource for value: webRTCSource
        /// </summary>
        WebRTCSource = 15
    }

    /// <summary>
    /// Converts <see cref="PathSourceType"/> to and from the JSON value
    /// </summary>
    public static class PathSourceTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="PathSourceType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static PathSourceType FromString(string value)
        {
            if (value.Equals("hlsSource"))
                return PathSourceType.HlsSource;

            if (value.Equals("redirect"))
                return PathSourceType.Redirect;

            if (value.Equals("rpiCameraSource"))
                return PathSourceType.RpiCameraSource;

            if (value.Equals("rtmpConn"))
                return PathSourceType.RtmpConn;

            if (value.Equals("rtmpsConn"))
                return PathSourceType.RtmpsConn;

            if (value.Equals("rtmpSource"))
                return PathSourceType.RtmpSource;

            if (value.Equals("rtspSession"))
                return PathSourceType.RtspSession;

            if (value.Equals("rtspSource"))
                return PathSourceType.RtspSource;

            if (value.Equals("rtspsSession"))
                return PathSourceType.RtspsSession;

            if (value.Equals("srtConn"))
                return PathSourceType.SrtConn;

            if (value.Equals("srtSource"))
                return PathSourceType.SrtSource;

            if (value.Equals("mpegtsSource"))
                return PathSourceType.MpegtsSource;

            if (value.Equals("rtpSource"))
                return PathSourceType.RtpSource;

            if (value.Equals("webRTCSession"))
                return PathSourceType.WebRTCSession;

            if (value.Equals("webRTCSource"))
                return PathSourceType.WebRTCSource;

            throw new NotImplementedException($"Could not convert value to type PathSourceType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="PathSourceType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static PathSourceType? FromStringOrDefault(string value)
        {
            if (value.Equals("hlsSource"))
                return PathSourceType.HlsSource;

            if (value.Equals("redirect"))
                return PathSourceType.Redirect;

            if (value.Equals("rpiCameraSource"))
                return PathSourceType.RpiCameraSource;

            if (value.Equals("rtmpConn"))
                return PathSourceType.RtmpConn;

            if (value.Equals("rtmpsConn"))
                return PathSourceType.RtmpsConn;

            if (value.Equals("rtmpSource"))
                return PathSourceType.RtmpSource;

            if (value.Equals("rtspSession"))
                return PathSourceType.RtspSession;

            if (value.Equals("rtspSource"))
                return PathSourceType.RtspSource;

            if (value.Equals("rtspsSession"))
                return PathSourceType.RtspsSession;

            if (value.Equals("srtConn"))
                return PathSourceType.SrtConn;

            if (value.Equals("srtSource"))
                return PathSourceType.SrtSource;

            if (value.Equals("mpegtsSource"))
                return PathSourceType.MpegtsSource;

            if (value.Equals("rtpSource"))
                return PathSourceType.RtpSource;

            if (value.Equals("webRTCSession"))
                return PathSourceType.WebRTCSession;

            if (value.Equals("webRTCSource"))
                return PathSourceType.WebRTCSource;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="PathSourceType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(PathSourceType value)
        {
            if (value == PathSourceType.HlsSource)
                return "hlsSource";

            if (value == PathSourceType.Redirect)
                return "redirect";

            if (value == PathSourceType.RpiCameraSource)
                return "rpiCameraSource";

            if (value == PathSourceType.RtmpConn)
                return "rtmpConn";

            if (value == PathSourceType.RtmpsConn)
                return "rtmpsConn";

            if (value == PathSourceType.RtmpSource)
                return "rtmpSource";

            if (value == PathSourceType.RtspSession)
                return "rtspSession";

            if (value == PathSourceType.RtspSource)
                return "rtspSource";

            if (value == PathSourceType.RtspsSession)
                return "rtspsSession";

            if (value == PathSourceType.SrtConn)
                return "srtConn";

            if (value == PathSourceType.SrtSource)
                return "srtSource";

            if (value == PathSourceType.MpegtsSource)
                return "mpegtsSource";

            if (value == PathSourceType.RtpSource)
                return "rtpSource";

            if (value == PathSourceType.WebRTCSession)
                return "webRTCSession";

            if (value == PathSourceType.WebRTCSource)
                return "webRTCSource";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PathSourceType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class PathSourceTypeJsonConverter : JsonConverter<PathSourceType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override PathSourceType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            PathSourceType? result = rawValue == null
                ? null
                : PathSourceTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the PathSourceType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pathSourceType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, PathSourceType pathSourceType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(pathSourceType.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PathSourceType"/>
    /// </summary>
    public class PathSourceTypeNullableJsonConverter : JsonConverter<PathSourceType?>
    {
        /// <summary>
        /// Returns a PathSourceType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override PathSourceType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            PathSourceType? result = rawValue == null
                ? null
                : PathSourceTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pathSourceType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, PathSourceType? pathSourceType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(pathSourceType?.ToString() ?? "null");
        }
    }
}
