// <auto-generated>
/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MediaMTX.API.Client;

namespace MediaMTX.API.Model
{
    /// <summary>
    /// RecordingSegment
    /// </summary>
    public partial class RecordingSegment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecordingSegment" /> class.
        /// </summary>
        /// <param name="start">start</param>
        [JsonConstructor]
        public RecordingSegment(Option<string> start = default)
        {
            StartOption = start;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Start
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> StartOption { get; private set; }

        /// <summary>
        /// Gets or Sets Start
        /// </summary>
        [JsonPropertyName("start")]
        public string Start { get { return this.StartOption; } set { this.StartOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RecordingSegment {\n");
            sb.Append("  Start: ").Append(Start).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RecordingSegment" />
    /// </summary>
    public class RecordingSegmentJsonConverter : JsonConverter<RecordingSegment>
    {
        /// <summary>
        /// Deserializes json to <see cref="RecordingSegment" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RecordingSegment Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> start = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "start":
                            start = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (start.IsSet && start.Value == null)
                throw new ArgumentNullException(nameof(start), "Property is not nullable for class RecordingSegment.");

            return new RecordingSegment(start);
        }

        /// <summary>
        /// Serializes a <see cref="RecordingSegment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="recordingSegment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RecordingSegment recordingSegment, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, recordingSegment, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RecordingSegment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="recordingSegment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RecordingSegment recordingSegment, JsonSerializerOptions jsonSerializerOptions)
        {
            if (recordingSegment.StartOption.IsSet && recordingSegment.Start == null)
                throw new ArgumentNullException(nameof(recordingSegment.Start), "Property is required for class RecordingSegment.");

            if (recordingSegment.StartOption.IsSet)
                writer.WriteString("start", recordingSegment.Start);
        }
    }
}
