// <auto-generated>
/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MediaMTX.API.Client;

namespace MediaMTX.API.Model
{
    /// <summary>
    /// RecordingList
    /// </summary>
    public partial class RecordingList : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecordingList" /> class.
        /// </summary>
        /// <param name="itemCount">itemCount</param>
        /// <param name="items">items</param>
        /// <param name="pageCount">pageCount</param>
        [JsonConstructor]
        public RecordingList(Option<long?> itemCount = default, Option<List<Recording>> items = default, Option<long?> pageCount = default)
        {
            ItemCountOption = itemCount;
            ItemsOption = items;
            PageCountOption = pageCount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ItemCount
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> ItemCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets ItemCount
        /// </summary>
        [JsonPropertyName("itemCount")]
        public long? ItemCount { get { return this.ItemCountOption; } set { this.ItemCountOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of Items
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Recording>> ItemsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [JsonPropertyName("items")]
        public List<Recording> Items { get { return this.ItemsOption; } set { this.ItemsOption = new Option<List<Recording>>(value); } }

        /// <summary>
        /// Used to track the state of PageCount
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> PageCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets PageCount
        /// </summary>
        [JsonPropertyName("pageCount")]
        public long? PageCount { get { return this.PageCountOption; } set { this.PageCountOption = new Option<long?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RecordingList {\n");
            sb.Append("  ItemCount: ").Append(ItemCount).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  PageCount: ").Append(PageCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RecordingList" />
    /// </summary>
    public class RecordingListJsonConverter : JsonConverter<RecordingList>
    {
        /// <summary>
        /// Deserializes json to <see cref="RecordingList" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RecordingList Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> itemCount = default;
            Option<List<Recording>> items = default;
            Option<long?> pageCount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "itemCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                itemCount = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "items":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                items = new Option<List<Recording>>(JsonSerializer.Deserialize<List<Recording>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "pageCount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                pageCount = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (itemCount.IsSet && itemCount.Value == null)
                throw new ArgumentNullException(nameof(itemCount), "Property is not nullable for class RecordingList.");

            if (items.IsSet && items.Value == null)
                throw new ArgumentNullException(nameof(items), "Property is not nullable for class RecordingList.");

            if (pageCount.IsSet && pageCount.Value == null)
                throw new ArgumentNullException(nameof(pageCount), "Property is not nullable for class RecordingList.");

            return new RecordingList(itemCount, items, pageCount);
        }

        /// <summary>
        /// Serializes a <see cref="RecordingList" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="recordingList"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RecordingList recordingList, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, recordingList, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RecordingList" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="recordingList"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RecordingList recordingList, JsonSerializerOptions jsonSerializerOptions)
        {
            if (recordingList.ItemsOption.IsSet && recordingList.Items == null)
                throw new ArgumentNullException(nameof(recordingList.Items), "Property is required for class RecordingList.");

            if (recordingList.ItemCountOption.IsSet)
                writer.WriteNumber("itemCount", recordingList.ItemCountOption.Value.Value);

            if (recordingList.ItemsOption.IsSet)
            {
                writer.WritePropertyName("items");
                JsonSerializer.Serialize(writer, recordingList.Items, jsonSerializerOptions);
            }
            if (recordingList.PageCountOption.IsSet)
                writer.WriteNumber("pageCount", recordingList.PageCountOption.Value.Value);
        }
    }
}
