// <auto-generated>
/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MediaMTX.API.Client;

namespace MediaMTX.API.Model
{
    /// <summary>
    /// Defines RTMPConnState
    /// </summary>
    public enum RTMPConnState
    {
        /// <summary>
        /// Enum Idle for value: idle
        /// </summary>
        Idle = 1,

        /// <summary>
        /// Enum Read for value: read
        /// </summary>
        Read = 2,

        /// <summary>
        /// Enum Publish for value: publish
        /// </summary>
        Publish = 3
    }

    /// <summary>
    /// Converts <see cref="RTMPConnState"/> to and from the JSON value
    /// </summary>
    public static class RTMPConnStateValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="RTMPConnState"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static RTMPConnState FromString(string value)
        {
            if (value.Equals("idle"))
                return RTMPConnState.Idle;

            if (value.Equals("read"))
                return RTMPConnState.Read;

            if (value.Equals("publish"))
                return RTMPConnState.Publish;

            throw new NotImplementedException($"Could not convert value to type RTMPConnState: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="RTMPConnState"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static RTMPConnState? FromStringOrDefault(string value)
        {
            if (value.Equals("idle"))
                return RTMPConnState.Idle;

            if (value.Equals("read"))
                return RTMPConnState.Read;

            if (value.Equals("publish"))
                return RTMPConnState.Publish;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="RTMPConnState"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(RTMPConnState value)
        {
            if (value == RTMPConnState.Idle)
                return "idle";

            if (value == RTMPConnState.Read)
                return "read";

            if (value == RTMPConnState.Publish)
                return "publish";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RTMPConnState"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class RTMPConnStateJsonConverter : JsonConverter<RTMPConnState>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override RTMPConnState Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            RTMPConnState? result = rawValue == null
                ? null
                : RTMPConnStateValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the RTMPConnState to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rTMPConnState"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, RTMPConnState rTMPConnState, JsonSerializerOptions options)
        {
            writer.WriteStringValue(rTMPConnState.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RTMPConnState"/>
    /// </summary>
    public class RTMPConnStateNullableJsonConverter : JsonConverter<RTMPConnState?>
    {
        /// <summary>
        /// Returns a RTMPConnState from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override RTMPConnState? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            RTMPConnState? result = rawValue == null
                ? null
                : RTMPConnStateValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rTMPConnState"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, RTMPConnState? rTMPConnState, JsonSerializerOptions options)
        {
            writer.WriteStringValue(rTMPConnState?.ToString() ?? "null");
        }
    }
}
