// <auto-generated>
/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MediaMTX.API.Client;

namespace MediaMTX.API.Model
{
    /// <summary>
    /// RTMPConn
    /// </summary>
    public partial class RTMPConn : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RTMPConn" /> class.
        /// </summary>
        /// <param name="bytesReceived">bytesReceived</param>
        /// <param name="bytesSent">bytesSent</param>
        /// <param name="created">created</param>
        /// <param name="id">id</param>
        /// <param name="inboundBytes">inboundBytes</param>
        /// <param name="outboundBytes">outboundBytes</param>
        /// <param name="outboundFramesDiscarded">outboundFramesDiscarded</param>
        /// <param name="path">path</param>
        /// <param name="query">query</param>
        /// <param name="remoteAddr">remoteAddr</param>
        /// <param name="state">state</param>
        /// <param name="user">user</param>
        [JsonConstructor]
        public RTMPConn(Option<int?> bytesReceived = default, Option<int?> bytesSent = default, Option<string> created = default, Option<Guid?> id = default, Option<int?> inboundBytes = default, Option<int?> outboundBytes = default, Option<int?> outboundFramesDiscarded = default, Option<string> path = default, Option<string> query = default, Option<string> remoteAddr = default, Option<RTMPConnState?> state = default, Option<string> user = default)
        {
            BytesReceivedOption = bytesReceived;
            BytesSentOption = bytesSent;
            CreatedOption = created;
            IdOption = id;
            InboundBytesOption = inboundBytes;
            OutboundBytesOption = outboundBytes;
            OutboundFramesDiscardedOption = outboundFramesDiscarded;
            PathOption = path;
            QueryOption = query;
            RemoteAddrOption = remoteAddr;
            StateOption = state;
            UserOption = user;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of State
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<RTMPConnState?> StateOption { get; private set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [JsonPropertyName("state")]
        public RTMPConnState? State { get { return this.StateOption; } set { this.StateOption = new Option<RTMPConnState?>(value); } }

        /// <summary>
        /// Used to track the state of BytesReceived
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> BytesReceivedOption { get; private set; }

        /// <summary>
        /// Gets or Sets BytesReceived
        /// </summary>
        [JsonPropertyName("bytesReceived")]
        [Obsolete]
        public int? BytesReceived { get { return this.BytesReceivedOption; } set { this.BytesReceivedOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of BytesSent
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> BytesSentOption { get; private set; }

        /// <summary>
        /// Gets or Sets BytesSent
        /// </summary>
        [JsonPropertyName("bytesSent")]
        [Obsolete]
        public int? BytesSent { get { return this.BytesSentOption; } set { this.BytesSentOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of Created
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CreatedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [JsonPropertyName("created")]
        public string Created { get { return this.CreatedOption; } set { this.CreatedOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new Option<Guid?>(value); } }

        /// <summary>
        /// Used to track the state of InboundBytes
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> InboundBytesOption { get; private set; }

        /// <summary>
        /// Gets or Sets InboundBytes
        /// </summary>
        [JsonPropertyName("inboundBytes")]
        public int? InboundBytes { get { return this.InboundBytesOption; } set { this.InboundBytesOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of OutboundBytes
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> OutboundBytesOption { get; private set; }

        /// <summary>
        /// Gets or Sets OutboundBytes
        /// </summary>
        [JsonPropertyName("outboundBytes")]
        public int? OutboundBytes { get { return this.OutboundBytesOption; } set { this.OutboundBytesOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of OutboundFramesDiscarded
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> OutboundFramesDiscardedOption { get; private set; }

        /// <summary>
        /// Gets or Sets OutboundFramesDiscarded
        /// </summary>
        [JsonPropertyName("outboundFramesDiscarded")]
        public int? OutboundFramesDiscarded { get { return this.OutboundFramesDiscardedOption; } set { this.OutboundFramesDiscardedOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of Path
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> PathOption { get; private set; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [JsonPropertyName("path")]
        public string Path { get { return this.PathOption; } set { this.PathOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of Query
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> QueryOption { get; private set; }

        /// <summary>
        /// Gets or Sets Query
        /// </summary>
        [JsonPropertyName("query")]
        public string Query { get { return this.QueryOption; } set { this.QueryOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of RemoteAddr
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> RemoteAddrOption { get; private set; }

        /// <summary>
        /// Gets or Sets RemoteAddr
        /// </summary>
        [JsonPropertyName("remoteAddr")]
        public string RemoteAddr { get { return this.RemoteAddrOption; } set { this.RemoteAddrOption = new Option<string>(value); } }

        /// <summary>
        /// Used to track the state of User
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> UserOption { get; private set; }

        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [JsonPropertyName("user")]
        public string User { get { return this.UserOption; } set { this.UserOption = new Option<string>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RTMPConn {\n");
            sb.Append("  BytesReceived: ").Append(BytesReceived).Append("\n");
            sb.Append("  BytesSent: ").Append(BytesSent).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  InboundBytes: ").Append(InboundBytes).Append("\n");
            sb.Append("  OutboundBytes: ").Append(OutboundBytes).Append("\n");
            sb.Append("  OutboundFramesDiscarded: ").Append(OutboundFramesDiscarded).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("  RemoteAddr: ").Append(RemoteAddr).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RTMPConn" />
    /// </summary>
    public class RTMPConnJsonConverter : JsonConverter<RTMPConn>
    {
        /// <summary>
        /// Deserializes json to <see cref="RTMPConn" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RTMPConn Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> bytesReceived = default;
            Option<int?> bytesSent = default;
            Option<string> created = default;
            Option<Guid?> id = default;
            Option<int?> inboundBytes = default;
            Option<int?> outboundBytes = default;
            Option<int?> outboundFramesDiscarded = default;
            Option<string> path = default;
            Option<string> query = default;
            Option<string> remoteAddr = default;
            Option<RTMPConnState?> state = default;
            Option<string> user = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "bytesReceived":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                bytesReceived = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "bytesSent":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                bytesSent = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "created":
                            created = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "inboundBytes":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                inboundBytes = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "outboundBytes":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                outboundBytes = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "outboundFramesDiscarded":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                outboundFramesDiscarded = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "path":
                            path = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "query":
                            query = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "remoteAddr":
                            remoteAddr = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "state":
                            string stateRawValue = utf8JsonReader.GetString();
                            if (stateRawValue != null)
                                state = new Option<RTMPConnState?>(RTMPConnStateValueConverter.FromStringOrDefault(stateRawValue));
                            break;
                        case "user":
                            user = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (bytesReceived.IsSet && bytesReceived.Value == null)
                throw new ArgumentNullException(nameof(bytesReceived), "Property is not nullable for class RTMPConn.");

            if (bytesSent.IsSet && bytesSent.Value == null)
                throw new ArgumentNullException(nameof(bytesSent), "Property is not nullable for class RTMPConn.");

            if (created.IsSet && created.Value == null)
                throw new ArgumentNullException(nameof(created), "Property is not nullable for class RTMPConn.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class RTMPConn.");

            if (inboundBytes.IsSet && inboundBytes.Value == null)
                throw new ArgumentNullException(nameof(inboundBytes), "Property is not nullable for class RTMPConn.");

            if (outboundBytes.IsSet && outboundBytes.Value == null)
                throw new ArgumentNullException(nameof(outboundBytes), "Property is not nullable for class RTMPConn.");

            if (outboundFramesDiscarded.IsSet && outboundFramesDiscarded.Value == null)
                throw new ArgumentNullException(nameof(outboundFramesDiscarded), "Property is not nullable for class RTMPConn.");

            if (path.IsSet && path.Value == null)
                throw new ArgumentNullException(nameof(path), "Property is not nullable for class RTMPConn.");

            if (query.IsSet && query.Value == null)
                throw new ArgumentNullException(nameof(query), "Property is not nullable for class RTMPConn.");

            if (remoteAddr.IsSet && remoteAddr.Value == null)
                throw new ArgumentNullException(nameof(remoteAddr), "Property is not nullable for class RTMPConn.");

            if (state.IsSet && state.Value == null)
                throw new ArgumentNullException(nameof(state), "Property is not nullable for class RTMPConn.");

            if (user.IsSet && user.Value == null)
                throw new ArgumentNullException(nameof(user), "Property is not nullable for class RTMPConn.");

            return new RTMPConn(bytesReceived, bytesSent, created, id, inboundBytes, outboundBytes, outboundFramesDiscarded, path, query, remoteAddr, state, user);
        }

        /// <summary>
        /// Serializes a <see cref="RTMPConn" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rTMPConn"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RTMPConn rTMPConn, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, rTMPConn, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RTMPConn" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rTMPConn"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RTMPConn rTMPConn, JsonSerializerOptions jsonSerializerOptions)
        {
            if (rTMPConn.CreatedOption.IsSet && rTMPConn.Created == null)
                throw new ArgumentNullException(nameof(rTMPConn.Created), "Property is required for class RTMPConn.");

            if (rTMPConn.PathOption.IsSet && rTMPConn.Path == null)
                throw new ArgumentNullException(nameof(rTMPConn.Path), "Property is required for class RTMPConn.");

            if (rTMPConn.QueryOption.IsSet && rTMPConn.Query == null)
                throw new ArgumentNullException(nameof(rTMPConn.Query), "Property is required for class RTMPConn.");

            if (rTMPConn.RemoteAddrOption.IsSet && rTMPConn.RemoteAddr == null)
                throw new ArgumentNullException(nameof(rTMPConn.RemoteAddr), "Property is required for class RTMPConn.");

            if (rTMPConn.UserOption.IsSet && rTMPConn.User == null)
                throw new ArgumentNullException(nameof(rTMPConn.User), "Property is required for class RTMPConn.");

            if (rTMPConn.BytesReceivedOption.IsSet)
                writer.WriteNumber("bytesReceived", rTMPConn.BytesReceivedOption.Value.Value);

            if (rTMPConn.BytesSentOption.IsSet)
                writer.WriteNumber("bytesSent", rTMPConn.BytesSentOption.Value.Value);

            if (rTMPConn.CreatedOption.IsSet)
                writer.WriteString("created", rTMPConn.Created);

            if (rTMPConn.IdOption.IsSet)
                writer.WriteString("id", rTMPConn.IdOption.Value.Value);

            if (rTMPConn.InboundBytesOption.IsSet)
                writer.WriteNumber("inboundBytes", rTMPConn.InboundBytesOption.Value.Value);

            if (rTMPConn.OutboundBytesOption.IsSet)
                writer.WriteNumber("outboundBytes", rTMPConn.OutboundBytesOption.Value.Value);

            if (rTMPConn.OutboundFramesDiscardedOption.IsSet)
                writer.WriteNumber("outboundFramesDiscarded", rTMPConn.OutboundFramesDiscardedOption.Value.Value);

            if (rTMPConn.PathOption.IsSet)
                writer.WriteString("path", rTMPConn.Path);

            if (rTMPConn.QueryOption.IsSet)
                writer.WriteString("query", rTMPConn.Query);

            if (rTMPConn.RemoteAddrOption.IsSet)
                writer.WriteString("remoteAddr", rTMPConn.RemoteAddr);

            if (rTMPConn.StateOption.IsSet)
            {
                var stateRawValue = RTMPConnStateValueConverter.ToJsonValue(rTMPConn.State.Value);
                writer.WriteString("state", stateRawValue);
            }
            if (rTMPConn.UserOption.IsSet)
                writer.WriteString("user", rTMPConn.User);
        }
    }
}
