// <auto-generated>
/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MediaMTX.API.Client;

namespace MediaMTX.API.Model
{
    /// <summary>
    /// Defines RTSPSessionState
    /// </summary>
    public enum RTSPSessionState
    {
        /// <summary>
        /// Enum Idle for value: idle
        /// </summary>
        Idle = 1,

        /// <summary>
        /// Enum Read for value: read
        /// </summary>
        Read = 2,

        /// <summary>
        /// Enum Publish for value: publish
        /// </summary>
        Publish = 3
    }

    /// <summary>
    /// Converts <see cref="RTSPSessionState"/> to and from the JSON value
    /// </summary>
    public static class RTSPSessionStateValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="RTSPSessionState"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static RTSPSessionState FromString(string value)
        {
            if (value.Equals("idle"))
                return RTSPSessionState.Idle;

            if (value.Equals("read"))
                return RTSPSessionState.Read;

            if (value.Equals("publish"))
                return RTSPSessionState.Publish;

            throw new NotImplementedException($"Could not convert value to type RTSPSessionState: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="RTSPSessionState"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static RTSPSessionState? FromStringOrDefault(string value)
        {
            if (value.Equals("idle"))
                return RTSPSessionState.Idle;

            if (value.Equals("read"))
                return RTSPSessionState.Read;

            if (value.Equals("publish"))
                return RTSPSessionState.Publish;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="RTSPSessionState"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(RTSPSessionState value)
        {
            if (value == RTSPSessionState.Idle)
                return "idle";

            if (value == RTSPSessionState.Read)
                return "read";

            if (value == RTSPSessionState.Publish)
                return "publish";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RTSPSessionState"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class RTSPSessionStateJsonConverter : JsonConverter<RTSPSessionState>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override RTSPSessionState Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            RTSPSessionState? result = rawValue == null
                ? null
                : RTSPSessionStateValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the RTSPSessionState to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rTSPSessionState"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, RTSPSessionState rTSPSessionState, JsonSerializerOptions options)
        {
            writer.WriteStringValue(rTSPSessionState.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RTSPSessionState"/>
    /// </summary>
    public class RTSPSessionStateNullableJsonConverter : JsonConverter<RTSPSessionState?>
    {
        /// <summary>
        /// Returns a RTSPSessionState from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override RTSPSessionState? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            RTSPSessionState? result = rawValue == null
                ? null
                : RTSPSessionStateValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rTSPSessionState"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, RTSPSessionState? rTSPSessionState, JsonSerializerOptions options)
        {
            writer.WriteStringValue(rTSPSessionState?.ToString() ?? "null");
        }
    }
}
