// <auto-generated>
/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MediaMTX.API.Client;

namespace MediaMTX.API.Model
{
    /// <summary>
    /// Defines WebRTCSessionState
    /// </summary>
    public enum WebRTCSessionState
    {
        /// <summary>
        /// Enum Read for value: read
        /// </summary>
        Read = 1,

        /// <summary>
        /// Enum Publish for value: publish
        /// </summary>
        Publish = 2
    }

    /// <summary>
    /// Converts <see cref="WebRTCSessionState"/> to and from the JSON value
    /// </summary>
    public static class WebRTCSessionStateValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="WebRTCSessionState"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static WebRTCSessionState FromString(string value)
        {
            if (value.Equals("read"))
                return WebRTCSessionState.Read;

            if (value.Equals("publish"))
                return WebRTCSessionState.Publish;

            throw new NotImplementedException($"Could not convert value to type WebRTCSessionState: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="WebRTCSessionState"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static WebRTCSessionState? FromStringOrDefault(string value)
        {
            if (value.Equals("read"))
                return WebRTCSessionState.Read;

            if (value.Equals("publish"))
                return WebRTCSessionState.Publish;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="WebRTCSessionState"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(WebRTCSessionState value)
        {
            if (value == WebRTCSessionState.Read)
                return "read";

            if (value == WebRTCSessionState.Publish)
                return "publish";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WebRTCSessionState"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class WebRTCSessionStateJsonConverter : JsonConverter<WebRTCSessionState>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override WebRTCSessionState Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            WebRTCSessionState? result = rawValue == null
                ? null
                : WebRTCSessionStateValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the WebRTCSessionState to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webRTCSessionState"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, WebRTCSessionState webRTCSessionState, JsonSerializerOptions options)
        {
            writer.WriteStringValue(webRTCSessionState.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WebRTCSessionState"/>
    /// </summary>
    public class WebRTCSessionStateNullableJsonConverter : JsonConverter<WebRTCSessionState?>
    {
        /// <summary>
        /// Returns a WebRTCSessionState from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override WebRTCSessionState? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            WebRTCSessionState? result = rawValue == null
                ? null
                : WebRTCSessionStateValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webRTCSessionState"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, WebRTCSessionState? webRTCSessionState, JsonSerializerOptions options)
        {
            writer.WriteStringValue(webRTCSessionState?.ToString() ?? "null");
        }
    }
}
