/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using MediaMTX.API.Api;
using MediaMTX.API.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace MediaMTX.API.Test.Api
{
    /// <summary>
    ///  Class for testing HLSApi
    /// </summary>
    public sealed class HLSApiTests : ApiTestsBase
    {
        private readonly IHLSApi _instance;

        public HLSApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IHLSApi>();
        }

        /// <summary>
        /// Test HlsMuxersGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task HlsMuxersGetAsyncTest()
        {
            string name = default;
            var response = await _instance.HlsMuxersGetAsync(name);
            var model = response.Ok();
            Assert.IsType<HLSMuxer>(model);
        }

        /// <summary>
        /// Test HlsMuxersList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task HlsMuxersListAsyncTest()
        {
            Client.Option<int> page = default;
            Client.Option<int> itemsPerPage = default;
            var response = await _instance.HlsMuxersListAsync(page, itemsPerPage);
            var model = response.Ok();
            Assert.IsType<HLSMuxerList>(model);
        }

        /// <summary>
        /// Test HlssessionsGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task HlssessionsGetAsyncTest()
        {
            string id = default;
            var response = await _instance.HlssessionsGetAsync(id);
            var model = response.Ok();
            Assert.IsType<HLSSession>(model);
        }

        /// <summary>
        /// Test HlssessionsKick
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task HlssessionsKickAsyncTest()
        {
            string id = default;
            var response = await _instance.HlssessionsKickAsync(id);
            var model = response.Ok();
            Assert.IsType<OK>(model);
        }

        /// <summary>
        /// Test HlssessionsList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task HlssessionsListAsyncTest()
        {
            Client.Option<int> page = default;
            Client.Option<int> itemsPerPage = default;
            var response = await _instance.HlssessionsListAsync(page, itemsPerPage);
            var model = response.Ok();
            Assert.IsType<HLSSessionList>(model);
        }
    }
}
