/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using MediaMTX.API.Api;
using MediaMTX.API.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace MediaMTX.API.Test.Api
{
    /// <summary>
    ///  Class for testing RecordingsApi
    /// </summary>
    public sealed class RecordingsApiTests : ApiTestsBase
    {
        private readonly IRecordingsApi _instance;

        public RecordingsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IRecordingsApi>();
        }

        /// <summary>
        /// Test RecordingsDeleteSegment
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RecordingsDeleteSegmentAsyncTest()
        {
            string recordingPath = default;
            string start = default;
            var response = await _instance.RecordingsDeleteSegmentAsync(recordingPath, start);
            var model = response.Ok();
            Assert.IsType<OK>(model);
        }

        /// <summary>
        /// Test RecordingsGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RecordingsGetAsyncTest()
        {
            string name = default;
            var response = await _instance.RecordingsGetAsync(name);
            var model = response.Ok();
            Assert.IsType<Recording>(model);
        }

        /// <summary>
        /// Test RecordingsList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RecordingsListAsyncTest()
        {
            Client.Option<int> page = default;
            Client.Option<int> itemsPerPage = default;
            var response = await _instance.RecordingsListAsync(page, itemsPerPage);
            var model = response.Ok();
            Assert.IsType<RecordingList>(model);
        }
    }
}
