/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using MediaMTX.API.Api;
using MediaMTX.API.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace MediaMTX.API.Test.Api
{
    /// <summary>
    ///  Class for testing RTMPApi
    /// </summary>
    public sealed class RTMPApiTests : ApiTestsBase
    {
        private readonly IRTMPApi _instance;

        public RTMPApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IRTMPApi>();
        }

        /// <summary>
        /// Test RtmpConnectionsGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtmpConnectionsGetAsyncTest()
        {
            string id = default;
            var response = await _instance.RtmpConnectionsGetAsync(id);
            var model = response.Ok();
            Assert.IsType<RTMPConn>(model);
        }

        /// <summary>
        /// Test RtmpConnsKick
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtmpConnsKickAsyncTest()
        {
            string id = default;
            var response = await _instance.RtmpConnsKickAsync(id);
            var model = response.Ok();
            Assert.IsType<OK>(model);
        }

        /// <summary>
        /// Test RtmpConnsList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtmpConnsListAsyncTest()
        {
            Client.Option<int> page = default;
            Client.Option<int> itemsPerPage = default;
            var response = await _instance.RtmpConnsListAsync(page, itemsPerPage);
            var model = response.Ok();
            Assert.IsType<RTMPConnList>(model);
        }

        /// <summary>
        /// Test RtmpsConnectionsGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtmpsConnectionsGetAsyncTest()
        {
            string id = default;
            var response = await _instance.RtmpsConnectionsGetAsync(id);
            var model = response.Ok();
            Assert.IsType<RTMPConn>(model);
        }

        /// <summary>
        /// Test RtmpsConnsKick
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtmpsConnsKickAsyncTest()
        {
            string id = default;
            var response = await _instance.RtmpsConnsKickAsync(id);
            var model = response.Ok();
            Assert.IsType<OK>(model);
        }

        /// <summary>
        /// Test RtmpsConnsList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtmpsConnsListAsyncTest()
        {
            Client.Option<int> page = default;
            Client.Option<int> itemsPerPage = default;
            var response = await _instance.RtmpsConnsListAsync(page, itemsPerPage);
            var model = response.Ok();
            Assert.IsType<RTMPConnList>(model);
        }
    }
}
