/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using MediaMTX.API.Api;
using MediaMTX.API.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace MediaMTX.API.Test.Api
{
    /// <summary>
    ///  Class for testing RTSPApi
    /// </summary>
    public sealed class RTSPApiTests : ApiTestsBase
    {
        private readonly IRTSPApi _instance;

        public RTSPApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IRTSPApi>();
        }

        /// <summary>
        /// Test RtspConnsGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtspConnsGetAsyncTest()
        {
            string id = default;
            var response = await _instance.RtspConnsGetAsync(id);
            var model = response.Ok();
            Assert.IsType<RTSPConn>(model);
        }

        /// <summary>
        /// Test RtspConnsList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtspConnsListAsyncTest()
        {
            Client.Option<int> page = default;
            Client.Option<int> itemsPerPage = default;
            var response = await _instance.RtspConnsListAsync(page, itemsPerPage);
            var model = response.Ok();
            Assert.IsType<RTSPConnList>(model);
        }

        /// <summary>
        /// Test RtspSessionsGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtspSessionsGetAsyncTest()
        {
            string id = default;
            var response = await _instance.RtspSessionsGetAsync(id);
            var model = response.Ok();
            Assert.IsType<RTSPSession>(model);
        }

        /// <summary>
        /// Test RtspSessionsKick
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtspSessionsKickAsyncTest()
        {
            string id = default;
            var response = await _instance.RtspSessionsKickAsync(id);
            var model = response.Ok();
            Assert.IsType<OK>(model);
        }

        /// <summary>
        /// Test RtspSessionsList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtspSessionsListAsyncTest()
        {
            Client.Option<int> page = default;
            Client.Option<int> itemsPerPage = default;
            var response = await _instance.RtspSessionsListAsync(page, itemsPerPage);
            var model = response.Ok();
            Assert.IsType<RTSPSessionList>(model);
        }

        /// <summary>
        /// Test RtspsConnsGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtspsConnsGetAsyncTest()
        {
            string id = default;
            var response = await _instance.RtspsConnsGetAsync(id);
            var model = response.Ok();
            Assert.IsType<RTSPConn>(model);
        }

        /// <summary>
        /// Test RtspsConnsList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtspsConnsListAsyncTest()
        {
            Client.Option<int> page = default;
            Client.Option<int> itemsPerPage = default;
            var response = await _instance.RtspsConnsListAsync(page, itemsPerPage);
            var model = response.Ok();
            Assert.IsType<RTSPConnList>(model);
        }

        /// <summary>
        /// Test RtspsSessionsGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtspsSessionsGetAsyncTest()
        {
            string id = default;
            var response = await _instance.RtspsSessionsGetAsync(id);
            var model = response.Ok();
            Assert.IsType<RTSPSession>(model);
        }

        /// <summary>
        /// Test RtspsSessionsKick
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtspsSessionsKickAsyncTest()
        {
            string id = default;
            var response = await _instance.RtspsSessionsKickAsync(id);
            var model = response.Ok();
            Assert.IsType<OK>(model);
        }

        /// <summary>
        /// Test RtspsSessionsList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RtspsSessionsListAsyncTest()
        {
            Client.Option<int> page = default;
            Client.Option<int> itemsPerPage = default;
            var response = await _instance.RtspsSessionsListAsync(page, itemsPerPage);
            var model = response.Ok();
            Assert.IsType<RTSPSessionList>(model);
        }
    }
}
