/*
 * MediaMTX API
 *
 * API of MediaMTX, a server and proxy that supports various protocols.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using MediaMTX.API.Api;
using MediaMTX.API.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace MediaMTX.API.Test.Api
{
    /// <summary>
    ///  Class for testing SRTApi
    /// </summary>
    public sealed class SRTApiTests : ApiTestsBase
    {
        private readonly ISRTApi _instance;

        public SRTApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ISRTApi>();
        }

        /// <summary>
        /// Test SrtConnsGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task SrtConnsGetAsyncTest()
        {
            string id = default;
            var response = await _instance.SrtConnsGetAsync(id);
            var model = response.Ok();
            Assert.IsType<SRTConn>(model);
        }

        /// <summary>
        /// Test SrtConnsKick
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task SrtConnsKickAsyncTest()
        {
            string id = default;
            var response = await _instance.SrtConnsKickAsync(id);
            var model = response.Ok();
            Assert.IsType<OK>(model);
        }

        /// <summary>
        /// Test SrtConnsList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task SrtConnsListAsyncTest()
        {
            Client.Option<int> page = default;
            Client.Option<int> itemsPerPage = default;
            var response = await _instance.SrtConnsListAsync(page, itemsPerPage);
            var model = response.Ok();
            Assert.IsType<SRTConnList>(model);
        }
    }
}
